### ISSUE TITLE
text_opacity ne marche pas

### ISSUE THREAD

**Issue by manpaint** [xvw/RPGMaker#2]
L'utilisation de text_opacity(100,0) (ou avec tout autre valeur d'opacity renvoie à l'erreur suivante:
![image](https://user-images.githubusercontent.com/45153555/54163097-303d0300-442e-11e9-99cb-9d828d75183c.png)

J'ai bien évidemment fait afficher un texte 

avec l'ID 100 avant d'exécuté cet Event Script.

**Comment by xvw** [comment]
Le script a été mis à jour. Merci beaucoup. 

Sinon, tu peux utiliser RME, qui offre bien plus de fonctionnalités : 
- https://github.com/RMEx/RME/wiki
- http://rmex.github.io/RMEDoc/

Cordialement. Xavier
