### ISSUE TITLE
unexpected $end, expecting ')'

### ISSUE THREAD

**Issue by manpaint** [xvw/RPGMaker#3]
Après avoir installé la dernièere version de DisplayText, l'erreur suivante se produit:

![unexcpected end](https://user-images.githubusercontent.com/45153555/54885331-5791c800-4e51-11e9-8f27-f3ba72b5a17b.PNG)

L'erreur survient lorsque il s'agit d'un évènement commun en processus parrallèle qui contient un text_opacity et que l'évènement arrive à sa fin, mis à part ceci tout se déroule comme prévu.

**Comment by xvw** [comment]
En général, cette erreur provient quand un appel de script est mal formé. Tu voudrais bien m'envoyer une capture d'écran de l'événement en processus parallèle ? 
Merci.

**Comment by manpaint** [comment]
Désolé pour la réponse tardive:

![common event text location](https://user-images.githubusercontent.com/45153555/56081827-91664680-5ddf-11e9-85b4-afa5f525caf0.png)

(il y a un autre évènement commun qui met l'image de base à l'id 100)

**Comment by xvw** [comment]
Tu es sur que c'est cet événement commun "spécifique" qui cause le soucis ?

**Comment by manpaint** [comment]
Je l'ai refait (j'avais désactiver le lanceur d'évènement pour des raison de testing) et ca marche maintenant, j'ignore totallement ce que j'ai fait de différent. Sûrement un problème d'évènement de ma part.

**Comment by xvw** [comment]
Cool :)
