### ISSUE TITLE
Problème lors du chargement de sauvegarde

### ISSUE THREAD

**Issue by manpaint** [xvw/RPGMaker#4]
Lors du chargement de sauvegarde, le profil attribué à du texte affiché ansi que sont formattage font des choses étranges:

Version normale:
![textglitch2](https://user-images.githubusercontent.com/45153555/60398874-349b4200-9b2b-11e9-857e-b42e5bd35828.png)
Version glitché:
![textglitch1](https://user-images.githubusercontent.com/45153555/60398878-4381f480-9b2b-11e9-964d-8c49274200b3.png)

Ce bug n'arrivent que parfois et les circonstance exactent me sont inconnue (parfois tout va bien après le chargement de sauvegarde. Ma théorie est que quelque chose ne se passent pas correctement lors du rafraichissement de texte lors de leur chargement.

**Comment by xvw** [comment]
J'essaie de regarder ça dans les jours à venir

**Comment by xvw** [comment]
Je ne sais pas si je te l'avais déjà demandé, mais as-tu essayé RME avec ton projet ?

**Comment by manpaint** [comment]
> Je ne sais pas si je te l'avais déjà demandé, mais as-tu essayé RME avec ton projet ?

Oui mais RME manque plusieurs fonction requises (ou du moins rien n'indique qu'elle sont présence / pas de documentation.

**Comment by xvw** [comment]
Les quelles ?

**Comment by manpaint** [comment]
De mes souvernirs il manquait le module DisplayText mais selon la documentation elle existe bel et bien (peut-être ai-je regarder au mauvais endroit?). Je vait essayer dès que j'aurais le temps.

**Comment by xvw** [comment]
https://github.com/RMEx/RME/wiki/D%C3%A9finitions-de-profils-et-couleurs-pour-l'afficheur-de-textes-%C3%A0-l'%C3%A9cran

Et dans la documentation tu peux utiliser la recherche et chercher text 😉

**Comment by xvw** [comment]
Ping ?

**Comment by manpaint** [comment]
> Ping ?

J'ai effectué des test. RME a effectivement une fonction pour display du texte mais les profils créé ne semble pas être compatible (je n'ai pas trouver comment les convertir pour usage avec RME). Aussi le jeu ramme à mort avec RME.

**Comment by xvw** [comment]
L'utilisation des profiles est plus simple. Pour le lag, tu as raison, ça fait des mois que je dois fixer ce problème :/ j'espère trouver le temps dans les jours à venir. 

J'ai tout de même une question, où est-ce que tu définis tes profiles de text actuellement ?

**Comment by manpaint** [comment]
> J'ai tout de même une question, où est-ce que tu définis tes profiles de text actuellement ?
Au tout début du jeu, un évènement commun est apeelé pour les défénir. Pour certaine action comme ouvrir l'inventaire ils sont définit à chaque que l'interface (en event) est appellé.

**Comment by xvw** [comment]
Ok. En fait il faut faire les profile et les couleurs dans un script vierge en dessous du script de texte. Surtout pas dans un appel de script. Ça devrait corriger le soucis.

**Comment by manpaint** [comment]
Cela semble en effet corriger le tout. Merci! Si c'est pas déjà le cas, il faudrais peut-être ajouter une telle mention dans la documentation du script.

**Comment by xvw** [comment]
Cool. 

> Si c'est pas déjà le cas, il faudrais peut-être ajouter une telle mention dans la documentation du script.

En fait, c'est expliqué comme ça : 

> Je conseil de créer les couleurs (comme les profils) dans un script vierge en dessous de ce script. Une fois qu'une couleur est enregistrée, elle peut être appelée via get_color(:nom_désiré).
